include:
  - component: gitlab.fhnw.ch/dps/module/fs25/fs25-group13/fs13-git-components/acr-build-component@main
    inputs:
      acr_login_server: "$ACR_LOGIN_SERVER"
      acr_username: "$ACR_USERNAME"
      acr_password: "$ACR_PASSWORD"
      project_name: "$CI_PROJECT_NAME"
      image_tag: "$CI_COMMIT_SHORT_SHA"
      directory: "ChatbotService"
      
  - component: gitlab.fhnw.ch/dps/module/fs25/fs25-group13/fs13-git-components/acr-push-component@main
    inputs:
      acr_login_server: "$ACR_LOGIN_SERVER"
      acr_username: "$ACR_USERNAME"
      acr_password: "$ACR_PASSWORD"
      project_name: "$CI_PROJECT_NAME"
      image_tag: "$CI_COMMIT_SHORT_SHA"